# Generated by Django 4.0.3 on 2022-05-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('section', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('focus_id', models.CharField(max_length=200)),
            ],
        ),
    ]
